modLoader="javafml"
loaderVersion="[41,)"
license="${license}"
logoBlur=false
issueTrackerURL="${issue_tracker}"
logoFile="${mod_id}_icon.png"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="${mod_author}"
description='''
${mod_description}
'''
[[dependencies.polymorph]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.polymorph]]
    modId="minecraft"
    mandatory=true
    versionRange="${forge_mc_version_range}"
    ordering="NONE"
    side="BOTH"
